title: Jet Noise Prediction Workshop
description: A community benchmark effort for jet noise CFD prediction
url: "https://aiaa-jnpw.github.io"
baseurl: ""

theme: minima


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

header_pages:
  - contact.md
  - about.md
  - downloads.md

